[common]
server_addr=47.103.75.238:9347
conn_type=tcp
vkey=REPLACE_WITH_NPS_CLIENT_VKEY
auto_reconnection=true
max_conn=1000
flow_limit=1000
rate_limit=1000
crypt=true
compress=true
disconnect_timeout=60
